[package]
name = "clipboard_cleaner"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard-win = "4.4.2"

[build-dependencies]
winres = "0.1"